#!/bin/sh
#
# @name Gazebo Propguards with ToF sensor
#
# @type Quadrotor
#

# Change x500_tof to exactly match your new folder name
PX4_SIM_MODEL=${PX4_SIM_MODEL:=propguards_tof}

# Keep this line! It loads the base quadcopter flight dynamics and tuning
. ${R}etc/init.d-posix/airframes/4001_gz_x500
